/*
 * Created on 4 mar 2017 ( Time 18:53:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.TIdCard;
import org.demo.bean.jpa.TIdCardEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TIdCardServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TIdCardServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TIdCardEntity' to 'TIdCard'
	 * @param tIdCardEntity
	 */
	public TIdCard mapTIdCardEntityToTIdCard(TIdCardEntity tIdCardEntity) {
		if(tIdCardEntity == null) {
			return null;
		}

		//--- Generic mapping 
		TIdCard tIdCard = map(tIdCardEntity, TIdCard.class);

		return tIdCard;
	}
	
	/**
	 * Mapping from 'TIdCard' to 'TIdCardEntity'
	 * @param tIdCard
	 * @param tIdCardEntity
	 */
	public void mapTIdCardToTIdCardEntity(TIdCard tIdCard, TIdCardEntity tIdCardEntity) {
		if(tIdCard == null) {
			return;
		}

		//--- Generic mapping 
		map(tIdCard, tIdCardEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}