/*
 * Created on 4 mar 2017 ( Time 18:53:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.TPerson;
import org.demo.bean.jpa.TPersonEntity;
import org.demo.bean.jpa.TIdCardEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TPersonServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TPersonServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TPersonEntity' to 'TPerson'
	 * @param tPersonEntity
	 */
	public TPerson mapTPersonEntityToTPerson(TPersonEntity tPersonEntity) {
		if(tPersonEntity == null) {
			return null;
		}

		//--- Generic mapping 
		TPerson tPerson = map(tPersonEntity, TPerson.class);

		//--- Link mapping ( link to TIdCard )
		if(tPersonEntity.getTIdCard() != null) {
			tPerson.setIdCardId(tPersonEntity.getTIdCard().getId());
		}
		return tPerson;
	}
	
	/**
	 * Mapping from 'TPerson' to 'TPersonEntity'
	 * @param tPerson
	 * @param tPersonEntity
	 */
	public void mapTPersonToTPersonEntity(TPerson tPerson, TPersonEntity tPersonEntity) {
		if(tPerson == null) {
			return;
		}

		//--- Generic mapping 
		map(tPerson, tPersonEntity);

		//--- Link mapping ( link : tPerson )
		if( hasLinkToTIdCard(tPerson) ) {
			TIdCardEntity tIdCard1 = new TIdCardEntity();
			tIdCard1.setId( tPerson.getIdCardId() );
			tPersonEntity.setTIdCard( tIdCard1 );
		} else {
			tPersonEntity.setTIdCard( null );
		}

	}
	
	/**
	 * Verify that TIdCard id is valid.
	 * @param TIdCard TIdCard
	 * @return boolean
	 */
	private boolean hasLinkToTIdCard(TPerson tPerson) {
		if(tPerson.getIdCardId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}