/*
 * Created on 4 mar 2017 ( Time 18:53:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.demo.bean.TPhone;
import org.demo.bean.jpa.TPhoneEntity;
import org.demo.bean.jpa.TPersonEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TPhoneServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TPhoneServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TPhoneEntity' to 'TPhone'
	 * @param tPhoneEntity
	 */
	public TPhone mapTPhoneEntityToTPhone(TPhoneEntity tPhoneEntity) {
		if(tPhoneEntity == null) {
			return null;
		}

		//--- Generic mapping 
		TPhone tPhone = map(tPhoneEntity, TPhone.class);

		//--- Link mapping ( link to TPerson )
		if(tPhoneEntity.getTPerson() != null) {
			tPhone.setPersonId(tPhoneEntity.getTPerson().getId());
		}
		return tPhone;
	}
	
	/**
	 * Mapping from 'TPhone' to 'TPhoneEntity'
	 * @param tPhone
	 * @param tPhoneEntity
	 */
	public void mapTPhoneToTPhoneEntity(TPhone tPhone, TPhoneEntity tPhoneEntity) {
		if(tPhone == null) {
			return;
		}

		//--- Generic mapping 
		map(tPhone, tPhoneEntity);

		//--- Link mapping ( link : tPhone )
		if( hasLinkToTPerson(tPhone) ) {
			TPersonEntity tPerson1 = new TPersonEntity();
			tPerson1.setId( tPhone.getPersonId() );
			tPhoneEntity.setTPerson( tPerson1 );
		} else {
			tPhoneEntity.setTPerson( null );
		}

	}
	
	/**
	 * Verify that TPerson id is valid.
	 * @param TPerson TPerson
	 * @return boolean
	 */
	private boolean hasLinkToTPerson(TPhone tPhone) {
		if(tPhone.getPersonId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}