/*
 * Created on 4 mar 2017 ( Time 18:53:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.TPerson;

/**
 * Business Service Interface for entity TPerson.
 */
public interface TPersonService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	TPerson findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<TPerson> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TPerson save(TPerson entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TPerson update(TPerson entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TPerson create(TPerson entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
