/*
 * Created on 4 mar 2017 ( Time 18:53:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service;

import java.util.List;

import org.demo.bean.TPhone;

/**
 * Business Service Interface for entity TPhone.
 */
public interface TPhoneService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	TPhone findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<TPhone> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TPhone save(TPhone entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TPhone update(TPhone entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TPhone create(TPhone entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
