/*
 * Created on 4 mar 2017 ( Time 18:53:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "t_person"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="t_person", catalog="testjpadb" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TPersonEntity.countAll", query="SELECT COUNT(x) FROM TPersonEntity x" )
} )
public class TPersonEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="PERSON_TYPE", nullable=false, length=31)
    private String     personType   ;

    @Column(name="FIRST_NAME", length=255)
    private String     firstName    ;

    @Column(name="LAST_NAME", length=255)
    private String     lastName     ;

	// "idCardId" (column "ID_CARD_ID") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="tPerson", targetEntity=TPhoneEntity.class)
    private List<TPhoneEntity> listOfTPhone;

    @ManyToOne
    @JoinColumn(name="ID_CARD_ID", referencedColumnName="id")
    private TIdCardEntity tIdCard     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TPersonEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : PERSON_TYPE ( VARCHAR ) 
    public void setPersonType( String personType ) {
        this.personType = personType;
    }
    public String getPersonType() {
        return this.personType;
    }

    //--- DATABASE MAPPING : FIRST_NAME ( VARCHAR ) 
    public void setFirstName( String firstName ) {
        this.firstName = firstName;
    }
    public String getFirstName() {
        return this.firstName;
    }

    //--- DATABASE MAPPING : LAST_NAME ( VARCHAR ) 
    public void setLastName( String lastName ) {
        this.lastName = lastName;
    }
    public String getLastName() {
        return this.lastName;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfTPhone( List<TPhoneEntity> listOfTPhone ) {
        this.listOfTPhone = listOfTPhone;
    }
    public List<TPhoneEntity> getListOfTPhone() {
        return this.listOfTPhone;
    }

    public void setTIdCard( TIdCardEntity tIdCard ) {
        this.tIdCard = tIdCard;
    }
    public TIdCardEntity getTIdCard() {
        return this.tIdCard;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(personType);
        sb.append("|");
        sb.append(firstName);
        sb.append("|");
        sb.append(lastName);
        return sb.toString(); 
    } 

}
