/*
 * Created on 4 mar 2017 ( Time 18:53:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.demo.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "t_phone"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="t_phone", catalog="testjpadb" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TPhoneEntity.countAll", query="SELECT COUNT(x) FROM TPhoneEntity x" )
} )
public class TPhoneEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NUMBER", length=255)
    private String     number       ;

	// "personId" (column "PERSON_ID") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="PERSON_ID", referencedColumnName="id")
    private TPersonEntity tPerson     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TPhoneEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NUMBER ( VARCHAR ) 
    public void setNumber( String number ) {
        this.number = number;
    }
    public String getNumber() {
        return this.number;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTPerson( TPersonEntity tPerson ) {
        this.tPerson = tPerson;
    }
    public TPersonEntity getTPerson() {
        return this.tPerson;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(number);
        return sb.toString(); 
    } 

}
