/*
 * Created on 4 mar 2017 ( Time 18:53:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.common;


/**
 * Keys constants.
 * 
 * @author Telosys Tools Generator
 *
 */
public class Constants {
	
	public final static String COMPOSITE_KEY_SEPARATOR = "|";

}