/*
 * Created on 4 mar 2017 ( Time 18:53:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.common;


/**
 * Keys constants for messages.
 * 
 * @author Telosys Tools Generator
 *
 */
public class MessagesKeys {
	
	// Keys for resources messages
	public static final String ID_MUST_DEFINE = "id.must.define";
	public static final String NOT_BLANK = "not.blank";
	
}