/*
 * Created on 4 mar 2017 ( Time 18:53:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import org.demo.bean.TIdCard;
import org.demo.bean.jpa.TIdCardEntity;
import java.util.Date;
import java.util.List;
import org.demo.business.service.TIdCardService;
import org.demo.business.service.mapping.TIdCardServiceMapper;
import org.demo.data.repository.jpa.TIdCardJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of TIdCardService
 */
@Component
@Transactional
public class TIdCardServiceImpl implements TIdCardService {

	@Resource
	private TIdCardJpaRepository tIdCardJpaRepository;

	@Resource
	private TIdCardServiceMapper tIdCardServiceMapper;
	
	@Override
	public TIdCard findById(Long id) {
		TIdCardEntity tIdCardEntity = tIdCardJpaRepository.findOne(id);
		return tIdCardServiceMapper.mapTIdCardEntityToTIdCard(tIdCardEntity);
	}

	@Override
	public List<TIdCard> findAll() {
		Iterable<TIdCardEntity> entities = tIdCardJpaRepository.findAll();
		List<TIdCard> beans = new ArrayList<TIdCard>();
		for(TIdCardEntity tIdCardEntity : entities) {
			beans.add(tIdCardServiceMapper.mapTIdCardEntityToTIdCard(tIdCardEntity));
		}
		return beans;
	}

	@Override
	public TIdCard save(TIdCard tIdCard) {
		return update(tIdCard) ;
	}

	@Override
	public TIdCard create(TIdCard tIdCard) {
		TIdCardEntity tIdCardEntity = tIdCardJpaRepository.findOne(tIdCard.getId());
		if( tIdCardEntity != null ) {
			throw new IllegalStateException("already.exists");
		}
		tIdCardEntity = new TIdCardEntity();
		tIdCardServiceMapper.mapTIdCardToTIdCardEntity(tIdCard, tIdCardEntity);
		TIdCardEntity tIdCardEntitySaved = tIdCardJpaRepository.save(tIdCardEntity);
		return tIdCardServiceMapper.mapTIdCardEntityToTIdCard(tIdCardEntitySaved);
	}

	@Override
	public TIdCard update(TIdCard tIdCard) {
		TIdCardEntity tIdCardEntity = tIdCardJpaRepository.findOne(tIdCard.getId());
		tIdCardServiceMapper.mapTIdCardToTIdCardEntity(tIdCard, tIdCardEntity);
		TIdCardEntity tIdCardEntitySaved = tIdCardJpaRepository.save(tIdCardEntity);
		return tIdCardServiceMapper.mapTIdCardEntityToTIdCard(tIdCardEntitySaved);
	}

	@Override
	public void delete(Long id) {
		tIdCardJpaRepository.delete(id);
	}

	public TIdCardJpaRepository getTIdCardJpaRepository() {
		return tIdCardJpaRepository;
	}

	public void setTIdCardJpaRepository(TIdCardJpaRepository tIdCardJpaRepository) {
		this.tIdCardJpaRepository = tIdCardJpaRepository;
	}

	public TIdCardServiceMapper getTIdCardServiceMapper() {
		return tIdCardServiceMapper;
	}

	public void setTIdCardServiceMapper(TIdCardServiceMapper tIdCardServiceMapper) {
		this.tIdCardServiceMapper = tIdCardServiceMapper;
	}

}
