/*
 * Created on 4 mar 2017 ( Time 18:53:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.validator;

import org.demo.bean.TPerson ;
import org.demo.common.MessagesKeys;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;

/**
 * Validator for entity TPerson
 * 
 * @author Telosys Tools Generator
 *
 */
public class TPersonValidator extends AbstractValidator<TPerson>{

    @Override
    public void validateEntity(TPerson entity, Errors errors) {

		ValidationUtils.rejectIfEmptyOrWhitespace(errors, "personType", MessagesKeys.NOT_BLANK);

    }
}