/*
 * Created on 4 mar 2017 ( Time 18:53:36 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package org.demo.validator;

import org.demo.bean.TPhone ;
import org.demo.common.MessagesKeys;
import org.springframework.validation.Errors;
import org.springframework.validation.ValidationUtils;

/**
 * Validator for entity TPhone
 * 
 * @author Telosys Tools Generator
 *
 */
public class TPhoneValidator extends AbstractValidator<TPhone>{

    @Override
    public void validateEntity(TPhone entity, Errors errors) {


    }
}