/*
 * Created on 4 mar 2017 ( Time 18:53:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.demo.bean.TIdCard;
import org.demo.business.service.TIdCardService;
import org.demo.web.listitem.TIdCardListItem;

/**
 * Spring MVC controller for 'TIdCard' management.
 */
@Controller
public class TIdCardRestController {

	@Resource
	private TIdCardService tIdCardService;
	
	@RequestMapping( value="/items/tIdCard",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<TIdCardListItem> findAllAsListItems() {
		List<TIdCard> list = tIdCardService.findAll();
		List<TIdCardListItem> items = new LinkedList<TIdCardListItem>();
		for ( TIdCard tIdCard : list ) {
			items.add(new TIdCardListItem( tIdCard ) );
		}
		return items;
	}
	
	@RequestMapping( value="/tIdCard",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<TIdCard> findAll() {
		return tIdCardService.findAll();
	}

	@RequestMapping( value="/tIdCard/{id}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public TIdCard findOne(@PathVariable("id") Long id) {
		return tIdCardService.findById(id);
	}
	
	@RequestMapping( value="/tIdCard",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public TIdCard create(@RequestBody TIdCard tIdCard) {
		return tIdCardService.create(tIdCard);
	}

	@RequestMapping( value="/tIdCard/{id}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public TIdCard update(@PathVariable("id") Long id, @RequestBody TIdCard tIdCard) {
		return tIdCardService.update(tIdCard);
	}

	@RequestMapping( value="/tIdCard/{id}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("id") Long id) {
		tIdCardService.delete(id);
	}
	
}
