/*
 * Created on 4 mar 2017 ( Time 18:53:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.demo.web.listitem;

import org.demo.bean.TPhone;
import org.demo.web.common.ListItem;

public class TPhoneListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public TPhoneListItem(TPhone tPhone) {
		super();

		this.value = ""
			 + tPhone.getId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = tPhone.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
